version: "2"
checks:
  method-lines:
    config:
      threshold: 30
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc.json
    indent:
      enabled: false
exclude_patterns:
  - utl/*
  - src/mscgen-inpage.js
  - src/script/lib/*
  - src/script/test/*
  - **node_modules**
